indent_style = "Block"
use_small_heuristics = "Max"
combine_control_expr = false
fn_single_line = true
imports_indent = "Visual"
merge_imports = true
match_block_trailing_comma = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
edition = "Edition2018"